export const APP_STRINGS = {
  // Profile Page
  PROFILE_TITLE: 'Профиль',
  NICKNAME: 'Никнейм',
  EMAIL: 'Email',
  ABOUT: 'О себе',
  PHONE: 'Телефон',
  EDIT_PROFILE: 'Редактировать профиль',
  SAVE: 'Сохранить',
  CANCEL: 'Отмена',
  TELL_ABOUT_YOURSELF: 'Расскажите о себе',
  PHONE_PLACEHOLDER: '+7XXXXXXXXXX',

  // Toast Messages
  PROFILE_UPDATED: 'Профиль обновлен',
  PROFILE_UPDATE_SUCCESS: 'Ваш профиль успешно обновлен.',
  PROFILE_UPDATE_ERROR: 'Не удалось обновить профиль. Попробуйте еще раз.',
  ERROR: 'Ошибка',

  // Index Page
  WELCOME_TITLE: 'Добро пожаловать в Мессенджер',
  WELCOME_SUBTITLE: 'Ваша платформа для обмена сообщениями в реальном времени.',
  SELECT_CONVERSATION: 'Выберите диалог',
  SELECT_CONVERSATION_DESCRIPTION: 'Выберите существующий диалог из списка слева или начните новую беседу',
  NEW_MESSAGE: 'Новое сообщение',

  // Contacts
  CONTACTS: 'Контакты',
  NO_CONTACTS: 'Пока нет контактов',
  CONTACT_REMOVED: 'Контакт удален',
  CONTACT_REMOVED_SUCCESS: 'Контакт успешно удален',
  CONTACT_REMOVE_ERROR: 'Не удалось удалить контакт. Попробуйте еще раз.',
  ADD_CONTACT: 'Добавить контакт',
  SEARCH_CONTACTS: 'Поиск контактов...',
  FRIEND_REQUESTS: 'Запросы в друзья',
  NO_FRIEND_REQUESTS: 'Нет запросов в друзья',
  ACCEPT: 'Принять',
  REJECT: 'Отклонить',
  FRIEND_REQUEST_ACCEPTED: 'Запрос в друзья принят',
  FRIEND_REQUEST_ACCEPTED_SUCCESS: 'Запрос в друзья успешно принят',
  FRIEND_REQUEST_ACCEPT_ERROR: 'Не удалось принять запрос в друзья. Попробуйте еще раз.',
  FRIEND_REQUEST_REJECTED: 'Запрос в друзья отклонен',
  FRIEND_REQUEST_REJECTED_SUCCESS: 'Запрос в друзья успешно отклонен',
  FRIEND_REQUEST_REJECT_ERROR: 'Не удалось отклонить запрос в друзья. Попробуйте еще раз.',
  FRIEND_REQUEST_SENT: 'Запрос в друзья отправлен',
  FRIEND_REQUEST_SENT_SUCCESS: 'Запрос в друзья успешно отправлен',
  FRIEND_REQUEST_SEND_ERROR: 'Не удалось отправить запрос в друзья. Попробуйте еще раз.',
  NO_USERS_FOUND: 'Пользователи не найдены',

  // Chat
  CHAT: 'Чат',
  CHATS: 'Чаты',
  NEW_CHAT: 'Новый чат',
  GROUP_CHAT: 'Групповой чат',
  DIRECT_CHAT: 'Личный чат',
  TYPE_MESSAGE: 'Введите сообщение...',
  SEND: 'Отправить',
  EDIT: 'Редактировать',
  DELETE: 'Удалить',
  MESSAGE_EDITED: 'Сообщение отредактировано',
  MESSAGE_EDITED_SUCCESS: 'Ваше сообщение успешно отредактировано',
  MESSAGE_DELETED: 'Сообщение удалено',
  MESSAGE_DELETED_SUCCESS: 'Ваше сообщение успешно удалено',
  MESSAGE_SENT: 'Сообщение отправлено',
  MESSAGE_SENT_SUCCESS: 'Ваше сообщение успешно отправлено',
  MESSAGE_SEND_ERROR: 'Не удалось отправить сообщение. Попробуйте еще раз.',
  MESSAGE_EDIT_ERROR: 'Не удалось отредактировать сообщение. Попробуйте еще раз.',
  MESSAGE_DELETE_ERROR: 'Не удалось удалить сообщение. Попробуйте еще раз.',
  NO_MESSAGES: 'Пока нет сообщений. Начните разговор!',
  PARTICIPANTS: 'участников',
  TYPING: 'печатает...',
  CONNECTED: 'Подключено',
  DISCONNECTED: 'Отключено',
  RECONNECTING: 'Переподключение...',
  CONNECTION_ERROR: 'Ошибка подключения',
  CHAT_NAME: 'Название чата',
  CREATE_CHAT: 'Создать чат',
  CHAT_CREATED: 'Чат создан',
  CHAT_CREATED_SUCCESS: 'Чат успешно создан',
  CHAT_CREATE_ERROR: 'Не удалось создать чат. Попробуйте еще раз.',
  CHAT_DELETED: 'Чат удален',
  CHAT_DELETED_SUCCESS: 'Чат успешно удален',
  CHAT_DELETE_ERROR: 'Не удалось удалить чат. Попробуйте еще раз.',
  CHAT_RENAMED: 'Чат переименован',
  CHAT_RENAMED_SUCCESS: 'Чат успешно переименован',
  CHAT_RENAME_ERROR: 'Не удалось переименовать чат. Попробуйте еще раз.',
  ADD_PARTICIPANT: 'Добавить участника',
  REMOVE_PARTICIPANT: 'Удалить участника',
  PARTICIPANT_ADDED: 'Участник добавлен',
  PARTICIPANT_ADDED_SUCCESS: 'Участник успешно добавлен',
  PARTICIPANT_ADD_ERROR: 'Не удалось добавить участника. Попробуйте еще раз.',
  PARTICIPANT_REMOVED: 'Участник удален',
  PARTICIPANT_REMOVED_SUCCESS: 'Участник успешно удален',
  PARTICIPANT_REMOVE_ERROR: 'Не удалось удалить участника. Попробуйте еще раз.',
} as const; 