export const APP_STRINGS = {
  // Navigation
  APP_NAME: 'MessengerRT',
  HOME: 'Home',
  PROFILE: 'Profile',
  LOGOUT: 'Logout',

  // Profile Page
  PROFILE_TITLE: 'Profile',
  NICKNAME: 'Nickname',
  EMAIL: 'Email',
  ABOUT: 'About',
  PHONE: 'Phone',
  EDIT_PROFILE: 'Edit Profile',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  TELL_ABOUT_YOURSELF: 'Tell us about yourself',
  PHONE_PLACEHOLDER: '+7XXXXXXXXXX',

  // Toast Messages
  PROFILE_UPDATED: 'Profile updated',
  PROFILE_UPDATE_SUCCESS: 'Your profile has been successfully updated.',
  PROFILE_UPDATE_ERROR: 'Failed to update profile. Please try again.',
  ERROR: 'Error',

  // Index Page
  WELCOME_TITLE: 'Welcome to MessengerRT',
  WELCOME_SUBTITLE: 'Your real-time messaging platform.',
  SELECT_CONVERSATION: 'Выберите диалог',
  SELECT_CONVERSATION_DESCRIPTION: 'Выберите существующий диалог из списка слева или начните новую беседу',
  NEW_MESSAGE: 'Новое сообщение',

  // Contacts
  CONTACTS: 'Contacts',
  NO_CONTACTS: 'No contacts yet',
  CONTACT_REMOVED: 'Contact removed',
  CONTACT_REMOVED_SUCCESS: 'Contact has been successfully removed',
  CONTACT_REMOVE_ERROR: 'Failed to remove contact. Please try again.',
  ADD_CONTACT: 'Add Contact',
  SEARCH_CONTACTS: 'Search contacts...',
  FRIEND_REQUESTS: 'Friend Requests',
  NO_FRIEND_REQUESTS: 'No friend requests',
  ACCEPT: 'Accept',
  REJECT: 'Reject',
  FRIEND_REQUEST_ACCEPTED: 'Friend request accepted',
  FRIEND_REQUEST_ACCEPTED_SUCCESS: 'Friend request has been successfully accepted',
  FRIEND_REQUEST_ACCEPT_ERROR: 'Failed to accept friend request. Please try again.',
  FRIEND_REQUEST_REJECTED: 'Friend request rejected',
  FRIEND_REQUEST_REJECTED_SUCCESS: 'Friend request has been successfully rejected',
  FRIEND_REQUEST_REJECT_ERROR: 'Failed to reject friend request. Please try again.',
  FRIEND_REQUEST_SENT: 'Friend request sent',
  FRIEND_REQUEST_SENT_SUCCESS: 'Friend request has been successfully sent',
  FRIEND_REQUEST_SEND_ERROR: 'Failed to send friend request. Please try again.',
  NO_USERS_FOUND: 'No users found',

  // Chat
  CHAT: 'Chat',
  CHATS: 'Chats',
  NEW_CHAT: 'New Chat',
  GROUP_CHAT: 'Group Chat',
  DIRECT_CHAT: 'Direct Chat',
  TYPE_MESSAGE: 'Type a message...',
  SEND: 'Send',
  EDIT: 'Edit',
  DELETE: 'Delete',
  MESSAGE_EDITED: 'Message Edited',
  MESSAGE_EDITED_SUCCESS: 'Your message has been edited successfully',
  MESSAGE_DELETED: 'Message Deleted',
  MESSAGE_DELETED_SUCCESS: 'Your message has been deleted successfully',
  MESSAGE_SENT: 'Message Sent',
  MESSAGE_SENT_SUCCESS: 'Your message has been sent successfully',
  MESSAGE_SEND_ERROR: 'Failed to send message. Please try again.',
  MESSAGE_EDIT_ERROR: 'Failed to edit message. Please try again.',
  MESSAGE_DELETE_ERROR: 'Failed to delete message. Please try again.',
  NO_MESSAGES: 'No messages yet. Start the conversation!',
  PARTICIPANTS: 'participants',
  TYPING: 'typing...',
  CONNECTED: 'Connected',
  DISCONNECTED: 'Disconnected',
  RECONNECTING: 'Reconnecting...',
  CONNECTION_ERROR: 'Connection Error',
  CHAT_NAME: 'Chat Name',
  CREATE_CHAT: 'Create Chat',
  CHAT_CREATED: 'Chat created',
  CHAT_CREATED_SUCCESS: 'Chat has been successfully created',
  CHAT_CREATE_ERROR: 'Failed to create chat. Please try again.',
  CHAT_DELETED: 'Chat deleted',
  CHAT_DELETED_SUCCESS: 'Chat has been successfully deleted',
  CHAT_DELETE_ERROR: 'Failed to delete chat. Please try again.',
  CHAT_RENAMED: 'Chat renamed',
  CHAT_RENAMED_SUCCESS: 'Chat has been successfully renamed',
  CHAT_RENAME_ERROR: 'Failed to rename chat. Please try again.',
  ADD_PARTICIPANT: 'Add Participant',
  REMOVE_PARTICIPANT: 'Remove Participant',
  PARTICIPANT_ADDED: 'Participant added',
  PARTICIPANT_ADDED_SUCCESS: 'Participant has been successfully added',
  PARTICIPANT_ADD_ERROR: 'Failed to add participant. Please try again.',
  PARTICIPANT_REMOVED: 'Participant removed',
  PARTICIPANT_REMOVED_SUCCESS: 'Participant has been successfully removed',
  PARTICIPANT_REMOVE_ERROR: 'Failed to remove participant. Please try again.',
} as const; 